# Generated by Django 3.2.3 on 2021-05-23 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=30)),
                ('delivery_status', models.CharField(choices=[('Ordered', 'Ordered'), ('Processing Order', 'Processing Order'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Ordered', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
